# SonarCloud Automatic Analysis Configuration
sonar.organization=bayly-ai
sonar.projectKey=Bayly-AI_HATH0R-CLI
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/.github/**,**/lib/**,**/packages/**,**/release/**,**/docs/**,**/contracts/**,**/packaging/**,**/scripts/**
sonar.cpd.exclusions=**
